### ISSUE TITLE
simple repeats file format - KeyError: 11

### ISSUE THREAD

**Issue by drvenki** [shenjia1/FirstSV#1]
Hi
I am trying to use FirstSV for prostate cancer cfdna data and I have encountered some errors while running. 

I have downloaded the simple repeats file from UCSC GoldenPath and I get the following error. 
```
Step1: extract softclip reads from bamfile
>>> start at Wed Apr  3 14:58:40 2019
<<< end at Wed Apr  3 14:58:57 2019
Step2: transfer samfile to fastafile
>>> start at Wed Apr  3 14:58:57 2019
<<< end at Wed Apr  3 14:58:57 2019
Step3: call sv from samfile
>>> start at Wed Apr  3 14:58:57 2019
Traceback (most recent call last):
  File "FirstSV.py", line 735, in <module>
    main()
  File "FirstSV.py", line 707, in main
    call_sv(sv_filename,sam,bp_threshold,sp_threshold,mp_threshold,samtools,ref,hard_filter,our_model)
  File "FirstSV.py", line 253, in call_sv
    if int(key[1]) in srregion[key[0]] or int(key[3]) in srregion[key[2]]:  #only one breakpoint in simple repeat region will be discarded
KeyError: '11'
```
The tool stops running after this. Could you please let me know what is wrong? 
Your paper sounds very interesting and I would like to run this tool on our data which has short fragment lengths.
Thanks in advance, 
Venki
Venkatesh Chellappa

**Comment by shenjia1** [comment]
> Hi
> I am trying to use FirstSV for prostate cancer cfdna data and I have encountered some errors while running.
> 
> I have downloaded the simple repeats file from UCSC GoldenPath and I get the following error.
> 
> ```
> Step1: extract softclip reads from bamfile
> >>> start at Wed Apr  3 14:58:40 2019
> <<< end at Wed Apr  3 14:58:57 2019
> Step2: transfer samfile to fastafile
> >>> start at Wed Apr  3 14:58:57 2019
> <<< end at Wed Apr  3 14:58:57 2019
> Step3: call sv from samfile
> >>> start at Wed Apr  3 14:58:57 2019
> Traceback (most recent call last):
>   File "FirstSV.py", line 735, in <module>
>     main()
>   File "FirstSV.py", line 707, in main
>     call_sv(sv_filename,sam,bp_threshold,sp_threshold,mp_threshold,samtools,ref,hard_filter,our_model)
>   File "FirstSV.py", line 253, in call_sv
>     if int(key[1]) in srregion[key[0]] or int(key[3]) in srregion[key[2]]:  #only one breakpoint in simple repeat region will be discarded
> KeyError: '11'
> ```
> The tool stops running after this. Could you please let me know what is wrong?
> Your paper sounds very interesting and I would like to run this tool on our data which has short fragment lengths.
> Thanks in advance,
> Venki
> Venkatesh Chellappa

Hi,
Do you convert the repeat file to bed format? And I think that you can change "11" to "chr11" and try it again.

Jia

**Comment by drvenki** [comment]
Hi Jia
Yes. I converted it to BED format. the chr column is as you suggest .. it is "chr11".
It would be useful if you add the simple repeats file you guys used to this repo here on github along with other files. 
I believe it is only 2.5mb in size, can you please upload your bed file. So everyone using FirstSV could download the same repeats bed file you used. 
Can we try?
Thanks,
Venki

**Comment by shenjia1** [comment]
> Hi Jia
> Yes. I converted it to BED format. the chr column is as you suggest .. it is "chr11".
> It would be useful if you add the simple repeats file you guys used to this repo here on github along with other files.
> I believe it is only 2.5mb in size, can you please upload your bed file. So everyone using FirstSV could download the same repeats bed file you used.
> Can we try?
> Thanks,
> Venki

Yes, it's a good suggestion. I have uploaded the simple repeats file I used. Thanks.
